### ISSUE TITLE
Day of week off by one day

### ISSUE THREAD

**Issue by jadefang68** [mdaskalov/flipperzero-clock#5]
The day of the week is showing up as off by one…i. e Sunday on a Saturday. 
![IMG_7618](https://github.com/user-attachments/assets/e65d291a-fa16-4c0a-b75b-c4027b0c5e41)

**Comment by mdaskalov** [comment]
For me it's right... 
Do you have the correct year? Can you confirm that you have the correct weekday shown in another app? Use the DCF77 clock sync, to check. What version are you using?

**Comment by jadefang68** [comment]
I am using the latest version of the clock, as it is on the app catalog, and flipper is at latest FW as wellSent from my iPhoneOn Aug 28, 2024, at 2:17 PM, Milko Daskalov ***@***.***> wrote:﻿
For me it's right... Can you confirm that you have the correct weekday shown in another app? What version are you using?

**Comment by mdaskalov** [comment]
Please check the year! 27.Aug is Wednesday in 2025. Try DCF77 Clock Sync - the weekday is shown there too.

**Comment by jadefang68** [comment]
I installed the DCF77 clock sync app, the day of the week is wrong in it as shown 😞Sent from my iPhoneOn Aug 29, 2024, at 2:41 AM, Milko Daskalov ***@***.***> wrote:﻿
Please check the year! 27.Aug is Wednesday in 2025. Try DCF77 Clock Sync - the weekday is shown there too.

**Comment by mdaskalov** [comment]
Can you confirm that the year is correct? I have no idea what's the issue as I am using flipper function to determine the weekday.

**Comment by jadefang68** [comment]
Well the year shows up correctly on the clock sync app, is there another way of verifying the flipper date settings?My iPhone also has all date settings in orderSent from my iPhoneOn Aug 30, 2024, at 6:10 AM, Milko Daskalov ***@***.***> wrote:﻿
Can you confirm that the year is correct? I have no idea what's the issue as I am using flipper function to determine the weekday.

**Comment by jadefang68** [comment]
Also I have checked flipper logs, and they are time stamped with the correct year, if that helpsSent from my iPhoneOn Aug 30, 2024, at 6:17 AM, Abelardo Garcia Jr ***@***.***> wrote:﻿Well the year shows up correctly on the clock sync app, is there another way of verifying the flipper date settings?My iPhone also has all date settings in orderSent from my iPhoneOn Aug 30, 2024, at 6:10 AM, Milko Daskalov ***@***.***> wrote:﻿
Can you confirm that the year is correct? I have no idea what's the issue as I am using flipper function to determine the weekday.

**Comment by mdaskalov** [comment]
You can report a bug from the iOS app. I have no idea what's wrong with your device.

Here are snapshots from today:

![image](https://github.com/user-attachments/assets/0098ac86-9df3-4706-856f-f8febce21486)


![image](https://github.com/user-attachments/assets/242bdde9-aaf1-46f7-b733-876ec2d26117)

**Comment by danielpatenaude** [comment]
I'm also seeing this issue. When using the "Clock" app I get the current date is correctly 09/13/2024. When using this "flipperzero-clock" app the date is Sep 13 Saturday (when it should be Friday). 

I have done no other customizations besides connected the flipper to my phone to install firmware and apps.

**Comment by mdaskalov** [comment]
I am sorry, but I can't reproduce it. 

Again, 13. Sep 2025 is Saturday, so it seems that it's the same problem. 

What phone do you use to synchronize? Have you tried qFlipper?

Please also create an issue at the official firmware and provide them details about your setup. I am using their library, which provides directly datetime and weekday. 

Have no idea how the time gets synced but obviously there is an issue with the year in some cases.

I have always used an iPhone for sync.

...here is what I use:

DateTime dt;
furi_hal_rtc_get_datetime(&dt);

**Comment by mdaskalov** [comment]
By digging deeper in the firmware I found out that the RTC could be controlled using CLI commands (check [here](https://docs.flipper.net/development/cli) for details how to use the command line interface) and that the weekday can be set to anything...

See what's current date/time - Last digit is weekday (4=Thursday)
```
>: date
2024-09-19 17:20:06 4
```
Change date/time (to 19.September 10:10 Monday) :
```
>: date 2024-09-19 10:10:00 1
New datetime is: 2024-09-19 10:10:00 1
```
...and if the clock app is running you will see the changes in realtime. With the last digit you can select any weekday.

I've also noticed that the time gets synced with the system clock once the mobile app or qFlipper is connected. The mobile app however changed the date/time only once (close the app and then start it again to update). 
So to find out what's going on you might set incorrect date/time and then sync. 

As I mentioned before: post your discoveries to the Flipper team so they can fix that for you.

Please also write here what's your setup - how do you sync and what's your locale.
